"""EU4 mod generator — PLACEHOLDER.

Writes the mod skeleton (descriptor + directory layout) to prove the output path, the
read-only/never-overwrite rules and the validation hook. Content files (history/countries,
history/provinces, common/country_tags, localisation) are generated in MVP step 8 after
their syntax is verified against EU4 modding docs; each template will cite its source.
"""

from __future__ import annotations

from pathlib import Path

from mega_converter.games.eu4.model import Eu4World

LAYOUT = ("common/country_tags", "common/countries", "history/countries", "history/provinces", "localisation")


class GeneratorError(RuntimeError):
    pass


def generate(world: Eu4World, out_dir: Path, mod_name: str) -> Path:
    mod_root = Path(out_dir) / mod_name
    if mod_root.exists():
        raise GeneratorError(f"{mod_root} exists; output directories are never overwritten")
    for sub in LAYOUT:
        (mod_root / sub).mkdir(parents=True)
    (Path(out_dir) / f"{mod_name}.mod").write_text(
        f'name="{mod_name}"\npath="mod/{mod_name}"\n# generated by Paradox Mega Campaign Converter\n',
        encoding="utf-8",
    )
    # TODO(MVP-8): write tags, country history, province history, localisation.
    return mod_root
